// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'authorName': string;
  'details': string;
  'file': string;
  'files': string;
  'letter': string;
  'path': string;
  'row': string;
  'selectedContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
